services:
  web:
    build: .
    container_name: books_api_web
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./data:/app/data
    restart: unless-stopped

  scraper:
    build: .
    container_name: books_scraper
    working_dir: /app
    volumes:
      - ./:/app
      - ./data:/app/data
    command: ["sh", "-c", "python -m app.part1 && python -m app.part2"]

  tests:
    build: .
    container_name: books_tests
    working_dir: /app
    volumes:
      - ./:/app
    command: ["sh", "-c", "pytest -q"]
